theme: jekyll-theme-modernist
title: Welcome to MachineLearningMD
description: This is a site dedicated to the junction between machine learning and molecular dynamics following to the work of Samuel Tovey
